apiVersion: apps/v1

kind: Deployment
metadata:
   labels:
     app: java
   name: java-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: java-tmp
  template:
    metadata:
      labels:
        app: java-tmp
    spec:
      containers:
        - image: tomcat:latest
          name: java-cont
